name: dev-cd

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build bundle
        run: yarn build

      - name: Build and push docker
        run: |
          docker build -t coderyashiro/crust-apps:latest .
          docker login -u ${{ secrets.DOCKER_DEV_HUB_USER_NAME }} -p ${{ secrets.DOCKER_DEV_HUB_PASSWORD }}
          docker push coderyashiro/crust-apps:latest
      - name: Upgrade apps
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker pull coderyashiro/crust-apps:latest
            cd /data2/docker/apps
            docker-compose up -d
          host: ${{ secrets.SSH_DEV_HOST }}
          user: ${{ secrets.SSH_DEV_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}